services:
  codebridge:
    build: .
    image: code-bridge:latest
    container_name: codebridge
    environment:
      - PORT=8501
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:rw
      - ./images:/app/images:rw
    restart: unless-stopped
